
.DELETE_ON_ERROR:

ORG := mmus
ORG_CAP := Mmus
MIRGENEDB_VERSION := 3.0


$(ORG)_mirgenedb$(MIRGENEDB_VERSION)_to_everything.tsv:
	ln -s ../0_miRNA_parsing/$@ ./$@

mgdb_3_$(ORG).premirna.tsv:
	ln -s ../1.1_retrieve_$(ORG_CAP)_ohnomirnas/$@ ./$@

mgdb_3_$(ORG).premirna_names.tsv: mgdb_3_$(ORG).premirna.ts
	cat $< | awk -F"\t" '{print $$9}' | strip_mirna_name 1 | sort | uniq > $@

mgdb_3_$(ORG).premirna_paralog_pairs.tsv: mgdb_3_$(ORG).premirna_names.tsv
	cat $< | get_mgdb_paralog_pairs | sort | uniq > $@

mgdb_3_$(ORG).premirna_paralog_pairs.extended_info.tsv: mgdb_3_$(ORG).premirna_paralog_pairs.tsv $(ORG)_mirgenedb$(MIRGENEDB_VERSION)_to_everything.tsv
	cat $(word 2, $^) | strip_mirna_name 1 | awk -F"\t" '{print $$1"\t"$$5"\t"$$9"\t"$$11"\t"$$12}' > mgdb_premirna_to_mirbase.dic;
	cat $(word 1, $^) | translate -a -d -j -v -e not_found mgdb_premirna_to_mirbase.dic 1 | translate -a -d -j -v -e not_found mgdb_premirna_to_mirbase.dic 6 | sort | uniq > $@


all_$(ORG)_ensembl_paralogmirna.tsv:
	ln -s ../../OhnomiRNAs/dataset/8_EnsemblParalogousMiRNAs/all_ensembl_paralogmirna.tsv.s ./$@

all_$(ORG)_ensembl_paralogmirna_clean.tsv: all_$(ORG)_ensembl_paralogmirna.tsv
	cat $< | awk -F"\t" '$$8!="" {print $$1"\t"$$7"\t"$$8"\t"$$9"\t"$$14}' | safe_col 5 |\
	awk -F"\t" '{ if ($$1 < $$3) { print $$1"\t"$$2"\t"$$3"\t"$$4"\t"$$5 } else { print $$3"\t"$$4"\t"$$1"\t"$$2"\t"$$5 } }' | sort | uniq > $@

all_$(ORG)_ensembl_paralogmirna_clean.mirgenedb_and_mirbase_info.tsv: all_$(ORG)_ensembl_paralogmirna_clean.tsv $(ORG)_mirgenedb$(MIRGENEDB_VERSION)_to_everything.tsv
	cat $(word 2, $^) | strip_mirna_name 1 | awk -F"\t" '{print $$5"\t"$$1"\t"$$11"\t"$$12}' | sort | uniq > dic;
	cat $(word 1, $^) | translate -a -d -j -v -e no_info dic 1 | translate -a -d -j -v -e no_info dic 6 | sort | uniq > $@;
	rm dic