.DELETE_ON_ERROR:

SPECIES := hsa

hsa-tissueItems.txt:
	wget -O$@ 'https://mirgenedb.org/static/data/$(SPECIES)/$(SPECIES)-tissueItems.txt'

hsa-tissueItems.tsv: hsa-tissueItems.txt
	sed 's/,/\t/g' $< > $@

hsa-tissueItems_clean.tsv: hsa-tissueItems.tsv
	cat $< | awk -F"\t" 'NR==1' > header;
	cat $< | awk -F"\t" 'NR>1' | strip_mirna_name 1 | sort | uniq > $@.noheader;
	cat header $@.noheader > $@;
	rm $@.noheader header