.DELETE_ON_ERROR:

SPECIES := hsa

hsa-tissueItems.txt:
	wget -O$@ 'https://mirgenedb.org/static/data/$(SPECIES)/$(SPECIES)-tissueItems.txt'

hsa-tissueItems.tsv: hsa-tissueItems.txt
	sed 's/,/\t/g' $< > $@

hsa-tissueItems_clean.tsv: hsa-tissueItems.tsv
	awk 'NR==1{print;next} {if ($2 != "") print}' $< > $@